#!/bin/bash
#
# When executed by git, this script always starts in the top of the
# repository
. "$(cd -P "${0%/*}/../.." && pwd)/bin/git-started-setup"
# `git log -1 HEAD` will give you the most recent commit
run_all_scripts util/git/post-commit.d
