#!/bin/bash
#
# When executed by git, this script always starts in the top of the
# repository
. "$(readlink -f "${0%/*}/../..")/bin/git-started-setup"

# Determine the revision we are comparing against
if git rev-parse --verify HEAD 1>/dev/null 2>&1; then
	AGAINST=HEAD
	debug "Diffing against head"
else
	# Initial commit: diff against an empty tree object
	AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
	debug "Diffing against an empty commit"
fi

# Iterate over each file that is being committed
ERROR_COUNT=0
RESULT=0

while read FILE; do
	# Show we are doing something to a file
	echo_prompt "$FILE"

	FILE_IGNORED=false
	FILE_DELETED=true

	# See if the file was deleted
	if [[ -f "$FILE" && ! -h "$FILE" ]]; then
		FILE_DELETED=false
	else
		debug "Detected $FILE was deleted"
	fi

	for DIR in $IGNORE_DIRS; do
		if [[ "$FILE" = $DIR* ]]; then
			FILE_IGNORED=true
			debug "Detected $FILE is to be ignored"
		fi
	done

	run_all_scripts util/git/pre-commit.d/

	if [ $? -ne 0 ]; then
		: $((ERROR_COUNT++))
	fi

	# Clear away the current file
	echo_clear_line
done < <(git diff-index --name-only --cached $AGAINST)

if [ $ERROR_COUNT -ne 0 ]; then
	echo ""
	echo "Correct any errors and commit again."
	exit 1
fi

exit 0
