#!/bin/bash

if [ -z "$1" ]; then
	test_for_program prettycss
else 
	local FILE="$1"

	prettycss $OPTIONS "$FILE" > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		lint_error "$FILE" "$TARGET"
		prettycss $OPTIONS "$FILE" 2>&1
	fi
fi
