#!/bin/bash

if [ -z "$1" ]; then
	test_for_program jslint
else
	local FILE="$1"

	jslint $OPTIONS "$FILE" > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		lint_error "$FILE"
		jslint $OPTIONS "$FILE" 2>&1
	fi
fi
