#!/bin/bash
#
# Avoid conflict markup by searching for seven "=", "<" or ">"
# in a row, which would comprise the entire line

if $FILE_DELETED || $FILE_IGNORED; then
	exit 0
fi

grep -q '^\(=======\|<<<<<<<\|>>>>>>>\)$' "$FILE"

if [ $? -eq 0 ]; then
	echo_clear_line
	grep -U3 --color=auto '^\(=======\|<<<<<<<\|>>>>>>>\)$' "$FILE"
	echo ""
	echo "Found conflict markup in file: $FILE"
	exit 1
fi

exit 0
