#!/bin/bash

if [ -z "$1" ]; then
	test_for_program sass
else
	local FILE="$1"

	sass $LINT_SASS_SASS_OPTIONS "$FILE" > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		lint_error "$FILE"
		jslint $LINT_SASS_SASS_OPTIONS "$FILE" 2>&1
	fi
fi
