#!/bin/bash

if [ -z "$1" ]; then
	test_for_program expand
else 
	local FILE="$1"
	local TEMP="$(temporary_file)"

	expand --tabs=4 --initial "$FILE" > "$TEMP" 2>&1

	if [ $? -ne 0 ]; then
		pretty_error "$TARGET"
		expand --tabs=4 --initial "$FILE" > "$TEMP" 2>&1
	else
		# mv does not preserve destination file permissions
		cat "$TEMP" > "$FILE"
		rm "$TEMP"
	fi
fi
