#!/bin/bash

if [ -z "$1" ]; then
    # Always pass saying we can run this pretty printer
    exit 0
else
    # Always fail indicating that we shouldn't have gotten this far
    echo "Lint checking has failed.  Are you missing a required linter?"
    echo "This is an intentional failure.  Double check your configuration."
    exit 1
fi
