#!/bin/bash

if [ -z "$1" ]; then
	test_for_program php
else 
	local FILE="$1"

	php -l $LINT_PHP_CLI_OPTIONS "$FILE" > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		lint_error "$FILE"
		php -l $LINT_PHP_CLI_OPTIONS "$FILE" 2>&1
	fi
fi
